Repository vostpt/bot, pull requests merged in 2019-06, with the labels that each got.

#72 [BOT-24] IPMA alerts sent to Twitter now includes image
  package-lock.json
  package.json
  src/images/VOSTPT_YellowWarning.png
  src/images/VOSTPT_aviso_Amarelo.png
  src/images/VOSTPT_aviso_Laranja.png
  src/images/VOSTPT_aviso_Vermelho.png
  src/services/Twitter.js
  src/services/Warnings.js
Labels: Feature

#75 [Feat/Fix] Bot behaviour
  src/commands/all.js
  src/events/message.js
  src/helpers/index.js
  src/triggers/greetings.js
  src/triggers/miscellaneous.js
Labels: Feature, bug, enhancement

#77 [Feat] Command op if works with just part of string
  src/commands/op.js
  src/services/ProCiv.js
Labels: enhancement

#78 [Feat] Add keywords in greetings
  src/triggers/greetings.js
Labels: enhancement

#81 [BOT-79] Bot reply when mentioned
  src/events/message.js
  src/triggers/miscellaneous.js
Labels: bug

#83 [BOT-14] Cooldowns
  .env.example
  config/bot.js
  src/app.js
  src/commands/acronym.js
  src/commands/alerts.js
  src/commands/all.js
  src/commands/earthquakes.js
  src/commands/op.js
  src/commands/rcm.js
  src/commands/weather.js
  src/events/message.js
  src/events/ready.js
Labels: enhancement

#84 [Fix] Execute bot without cooldown env variable
  config/bot.js
Labels: bug

#86 [Feat] In ?commands, bot now reacts instead of replying confirmation m…
  src/events/message.js
Labels: enhancement

#91 [Fix] Message formatting
  src/commands/all.js
  src/commands/op.js
  src/services/Fires.js
Labels: bug
