Repository vostpt/bot, pull requests merged in 2019-04, with the labels that each got.

#7 [Feat] ESLint: JS rules for everyone
  .eslintignore
  .eslintrc.js
  .prettierrc
  bot.js
  package-lock.json
  package.json
  src/bot.js
Labels: enhancement

#16 Added comments in Warnings and Earthquakes
  src/services/Earthquakes.js
  src/services/Warnings.js
Labels: enhancement

#35 [Docs] Contribution guide
  CONTRIBUTING.md
Labels: enhancement

#36 [Feat] Travis CI pipeline
  .travis.yml
  package.json
  src/app.js
  src/services/Earthquakes.js
  src/services/Warnings.js
Labels: Feature

#41 [BOT-13] Comments in '/services' code)
  src/services/Earthquakes.js
  src/services/Fires.js
  src/services/ProCiv.js
  src/services/Warnings.js
  src/services/Weather.js
  src/services/Winds.js
Labels: enhancement

#46 [BOT-13] Comments in /commands code
  src/commands/acronym.js
  src/commands/alerts.js
  src/commands/all.js
  src/commands/earthquakes.js
  src/commands/op.js
  src/commands/rcm.js
  src/commands/weather.js
  src/services/Warnings.js
Labels: Feature, bug
